version: "3"

services:

  runtime-setup:
    image: swift-package-collection-generator:20.04-5.7
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.7"

  test:
    image: swift-package-collection-generator:20.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-package-collection-generator:20.04-5.7
